### ISSUE TITLE
International Checkout Bug

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-storyteller#31]
Anytime a country outside US is selected, whether manually, via autofill or loaded on page load, the state field should show the Other State Providence box not the states drop down
![image002](https://cloud.githubusercontent.com/assets/11448089/24306614/647e6608-107e-11e7-9b9b-47a1e67fed83.jpg)
![image003](https://cloud.githubusercontent.com/assets/11448089/24306613/647e52f8-107e-11e7-8c9e-8bba7024e9fc.jpg)
![image004](https://cloud.githubusercontent.com/assets/11448089/24306615/6482d1ac-107e-11e7-8c8c-5f56c0d4fb3b.jpg)

**Comment by influxweb** [comment]
What browser/OS are you seeing this issue on?

**Comment by mivajenn** [comment]
Well, I'm not having the issue on my computer - Sam Newbold is and his client customers around the world are. I'll see if I can get some idea of what they are using. It's both on client's mac and Sam's pc.

**Comment by mivajenn** [comment]
Here's the note from Sam:
I tested in Safari, Chrome and Firefox. Replicated in all three.
 
I’m on a PC.
 
 
The scripts.js file that Jeremy updated (I'll send to you on email) ended up fixing the clients issue. State/province field changes to text field now rather than retain the US states drop-down menu.
 
 
https://moodyleather.com
 
snewbold@miva.com
Mivatest123
Saved Address: Australia

**Comment by influxweb** [comment]
I have made an update to the Storyteller demonstration site. Can you test and let me know the results?

**Comment by mivajenn** [comment]
A NOTE FROM SAM...

Still functioning the same. I guess the big question is this…
Is it meant to function this way?
I understand that the selection in the State/Province field changes to “Outside US”, but the other themes change to a text field where you can enter the traditional “Other State/Province” info.
Maybe this theme is supposed to do this? Not sure. From a user perspective this is confusing.
![capture-levels](https://cloud.githubusercontent.com/assets/11448089/24310272/7af172d2-108c-11e7-94bc-9d672b595643.JPG)
![capture-storyteller](https://cloud.githubusercontent.com/assets/11448089/24310280/8906fee6-108c-11e7-8053-4a7e72825369.JPG)


See attached comparison of Levels vs Storyteller OCST page when using saved address.
 
-Sam

**Comment by influxweb** [comment]
I have updated the functions again. Can the site be retested after clearing the browser cache?
